# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  # centos7を使用
  config.vm.box = "centos/7"
  config.vm.synced_folder '../', '/vagrant', :type => 'nfs'
  # ホストマシンの3000番ポートをゲストOSの2000番ポートへフォワード¬
  config.vm.network 'private_network', ip: '192.168.33.20'
  config.vm.network "forwarded_port", guest: 2000, host: 3000
  config.vm.provider "virtualbox" do |vb|
   # VirtualBoxのGUI上の名前を設定
   vb.name = "centos7"
   # メモリは2048MBに設定
   vb.memory = "2048"
  end
end
